### ISSUE TITLE
README assumes the community alire index is already on the user's system.

### ISSUE THREAD

**Issue by berkeleynerd** [simonjwright/alire-index.mac#3]
The bootstrapping instructions in the README assume the Alire community index is already on the user's system. If it is not, the following command will fail at `--before=community \` :

```
 alr index \
   --add=git+https://github.com/simonjwright/alire-index.mac.git \
   --before=community \
   --name=index_for_mac
```

It might be best to direct the user to prime the community index before issuing the aforementioned statement.

**Comment by simonjwright** [comment]
Good point! Fixed (I hope) at d3d5971.
